apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
spec:
  storageClassName: cinder-nova
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
